language: node_js
node_js:
- '8.7'
dist: trusty
before_script:
#- npm list -g cordova --depth=0 || npm install -g cordova
#- npm list -g ionic --depth=0 || npm install -g ionic
- npm list -g firebase-tools --depth=0 || npm install -g firebase-tools
script:
#- ls
#- npm install
#- mkdir www
#- ionic platform add browser
#- ionic build browser --prod
- cd functions
- npm install
after_success:
- $TRAVIS_BUILD_DIR/deploy.sh m4m-simsim
cache:
  directories:
#    - $(npm config get prefix)/bin/cordova
#    - $(npm config get prefix)/bin/ionic
    - $(npm config get prefix)/bin/firebase-tools
    - node_modules
notifications:
  email: false
  webhooks: https://travis.webhooks.m4m.io
